### PR TITLE
adding coinbase connector

### PR DESCRIPTION
**Pull request by arvindpatel24**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by manojradhakrishnan** [comment]
Should a connector integration PR specific to coinbase touch so many files across other connectors? 

If this is related to `supported payment methods` error handling, how to minimize the surface area of such a change?

**Comment by manojradhakrishnan** [comment]
Should a connector integration PR specific to coinbase touch so many files across other connectors? 

If this is related to `supported payment methods` error handling, how to minimize the surface area of such a change?

**Comment by arvindpatel24** [comment]
> Should a connector integration PR specific to coinbase touch so many files across other connectors?
> 
> If this is related to `supported payment methods` error handling, how to minimize the surface area of such a change?

**Comment by arvindpatel24** [comment]
> Should a connector integration PR specific to coinbase touch so many files across other connectors?
> 
> If this is related to `supported payment methods` error handling, how to minimize the surface area of such a change?

Yes, it is because of adding new payment method(crypto), which was not handled in few other connectors if any new payment method got added. But now I added the default case in other connectors too, so we don't need to change any other connector's files, if we add any new payment method

**Comment by Narayanbhat166** [comment]
Can you please provide a reason as to why this PR was closed?

**Comment by arvindpatel24** [comment]
This was a forked branch with my personal account. At the time of raising this PR, I didn't have the write access for juspay/hyperswitch repo. After getting access, me and @jagan-jaya created new branch `opennode-v2`

**Pull request closed without merging**
