### PR TITLE
feat(payments): Add audit events for PaymentApprove update

### LINKED ISSUE #4680: Add audit events for PaymentApprove update
Created from #4525 

This covers adding events for PaymentApprove operation

This event should include the payment data similar to [PaymentCancel](https://github.com/juspay/hyperswitch/pull/4166)

It should also include any metadata for the event  
e.g reason for payment rejection, error codes, rejection source etc

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

### PR DESCRIPTION
**Pull request by Rutam21**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR adds an Audit event for the PaymentApprove operation.

### Additional Changes

- [x] This PR modifies the files below

- `crates/router/src/core/payments/operations/payment_approve.rs`
- `crates/router/src/events/audit_events.rs`

## Motivation and Context

This PR fixes #4680 

## How did you test it

This requires FRM related flows to be tested, and may not be tested locally.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

### CODE REVIEW

**Comment by Rutam21** [comment]
Please review and suggest changes, if any.

cc: @Isampras @ShivanshMathurJuspay @ivor11

**Comment by lsampras** [comment]
Hey @Rutam21 ,
Can you share the event json or a screenshot of the event,
Can refer to pr https://github.com/juspay/hyperswitch/pull/4166 for reference.

**Comment by Rutam21** [comment]
@lsampras I checked #4166, can you please point me out how I can get a event screenhsot or event json for this update? It seems like you were using something similar to Postman to hit the API endpoint. If you could please let me know the steps, I would follow along and update.

**Comment by maverox** [comment]
> @lsampras I checked #4166, can you please point me out how I can get a event screenhsot or event json for this update? It seems like you were using something similar to Postman to hit the API endpoint. If you could please let me know the steps, I would follow along and update.

For the UI in this screenshot, you can find the docs to set up Kafka, kafka-ui (the interface in the screenshot) and ClickHouse using Docker Compose here: https://github.com/juspay/hyperswitch/tree/main/crates/analytics/docs

and then try generating said events and monitor logs in kafka-ui.

Also the docs are self-explanatory but still if in any doubt ping us in [this](https://hyperswitch-io.slack.com/archives/C04JXRZ338A) slack channel

**Comment by Rutam21** [comment]
@maverox I tried updating the respective `toml` files and then starting the app using docker-compose. But this errors out while starting the `hyperswitch-server-1`. Please let me know if there are some additional settings that I am missing here. Thanks.

Screenshot 2024-10-31 050533

**Review by tsdk02 — DISMISSED** [review]

**Comment by Chethan-rao** [comment]
> @maverox I tried updating the respective `toml` files and then starting the app using docker-compose. But this errors out while starting the `hyperswitch-server-1`. Please let me know if there are some additional settings that I am missing here. Thanks.
> 
> Screenshot 2024-10-31 050533

@Rutam21 Could you check the logs of the failed container

**Comment by Rutam21** [comment]
@Chethan-rao Could you please point me where I can access those logs? I tried to run `docker compose` following the steps at https://github.com/juspay/hyperswitch/tree/main/crates/analytics/docs. 

Also, I found out that the same error occurs when I try to run it on the `main` branch as well. It could be more of a local setup issue on Windows rather than a PR-specific issue.

Screenshot 2024-11-06 030554

**Review by Chethan-rao — DISMISSED** [review]

**Comment by Rutam21** [comment]
@likhinbopanna The merge conflicts are resolved. You can add it back to the merge queue now. Thanks.

**Review by tsdk02 — APPROVED** [review]

**Review by Chethan-rao — APPROVED** [review]

**Pull request merged**
