### PR TITLE
fix(analytics): added hs latency to api event for paymentconfirm call

### PR DESCRIPTION
**Pull request by harsh-sharma-juspay**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
added hs latency to api event for paymentconfirm call 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by harsh-sharma-juspay** [comment]
Screenshot 2023-11-05 at 10 04 15 PM

**Comment by harsh-sharma-juspay** [comment]
Screenshot 2023-11-05 at 10 05 23 PM

**Review by BallaNitesh — APPROVED** [review]

**Comment by likhinbopanna** [comment]
@harsh-sharma-juspay Can you please add Curl or the test cases ?

**Comment by harsh-sharma-juspay** [comment]
```curl --location --request POST 'http://localhost:8080/payments/pay_gXXRRnbhRIhw1eekNecY/confirm' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: dev_pqyZ40N2o1N8LCxPFLgcXiKxpmHabvL4fQNhQApZx4UjiIMe0CCXTETHggYRSfWj' \
--data-raw '{}'```

**Pull request merged**
