### PR TITLE
feat(connector): [Rapyd] Use connector_response_reference_id as reference to merchant

### LINKED ISSUE #2346: [FEATURE]: [Rapyd] Use `connector_response_reference_id` as reference to merchant
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- Please refer to the Rapyd API documentation [here](https://docs.rapyd.net/en/create-payment.html). In the payment response, there is a field called `merchant_reference_id` (an optional field). This `merchant_reference_id` needs to be mapped to the `connector_response_reference_id`.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by tejas-raskar**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Fixes #2346 

## How did you test it?

Make any Payment for connector Rapyd and see that you are getting "reference_id" field in the payments response of hyperswitch. It should not be null.

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by srujanchikke — CHANGES_REQUESTED** [review]

**Comment by swangi-kumari** [comment]
Hey @tejas-raskar ,
Pls address the CI fails
Run `cargo +nightly` fmt for formatting.

**Comment by swangi-kumari** [comment]
Hey @tejas-raskar ,
Thanks for your interest in contributing to hyperswitch.
Let us know if you need any assistance from our end.
Also, even if hacktoberfest is over, we should celebrate open source everyday and we are open for more contributions from you.
We would still be rewarding folks with goodies even if the PR gets merged post hacktoberfest.
May the Source be with you!

**Comment by tejas-raskar** [comment]
Hey @swangi-kumari,
I will still be working on this Issue. I am currently learning about Rust simultaneously. 
Will update you if any help is needed.
Thank you.

**Comment by swangi-kumari** [comment]
Hey @tejas-raskar ,
Are you still working o this PR?
Can you please fix the failing CI checks?
Let us know if you need any assistance from our end.

**Comment by deepanshu-iiitu** [comment]
Hi @tejas-raskar 
There are some conflicts in crates/router/src/connector/rapyd/transformers.rs
Please resolve them.

**Comment by tejas-raskar** [comment]
Hi @deepanshu-iiitu,
Sorry for the delay. I will look into the errors and try to resolve them at the earliest. Will keep you updated.

**Comment by gorakhnathy7** [comment]
Hey @tejas-raskar Any update when we can expect the changes to be done.

**Comment by tejas-raskar** [comment]
Hey @gorakhnathy7, I am working on it. Will complete it by the weekend at most.

**Comment by tejas-raskar** [comment]
The issue seems to be fixed by #6302. Do I need to close this PR?

**Comment by gorakhnathy7** [comment]
Hey @tejas-raskar As there was a pro-longed inactivity from your end. we had assigned the issue to someone else, and that PR has closed the issue.

Thanks for your efforts. Kindly pick another issue from here - https://github.com/juspay/hyperswitch/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee

**Pull request closed without merging**
