### PR TITLE
feat(db): Implement `ReverseLookupInterface` for `MockDb`

### LINKED ISSUE #1115: [FEATURE] Implement `ReverseLookupInterface` for `MockDb`
Spin out from https://github.com/juspay/hyperswitch/issues/172. Please refer to that issue for more information.

### PR DESCRIPTION
**Pull request by dalprahcd**
Implement the missing implementation of `MockDb` for `ReverseLookup`

Closes #1115

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by SanchithHegde — APPROVED** [review]
Looks good to me!

Thanks for the PR, @dalprahcd!

**Comment by SanchithHegde** [comment]
Also, please address the merge conflicts.

**Review by ThisIsMani — DISMISSED** [review]

**Comment by dalprahcd** [comment]
I have addressed the merging conflicts. Also, I noticed changes in the `Cargo.lock` file, should I have committed them as well?

**Review by ThisIsMani — APPROVED** [review]

**Comment by SanchithHegde** [comment]
> I noticed changes in the `Cargo.lock` file, should I have committed them as well?

Yes please.

**Comment by dalprahcd** [comment]
Done.

**Review by SanchithHegde — APPROVED** [review]

**Review by ThisIsMani — APPROVED** [review]

**Review by Narayanbhat166 — APPROVED** [review]

**Pull request merged**
