### PR TITLE
refactor(connector): [Square] remove default case handling

### PR DESCRIPTION
**Pull request by HeetVekariya**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- Fix issue #2286 
- Changes to be made : Remove default case handling
- File changed: ```transformers.rs``` (crates/router/src/connector/square/transformers.rs)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

https://github.com/juspay/hyperswitch/issues/2286

## How did you test it?

No test cases. As In this PR only error message have been populated for all default cases.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by HeetVekariya** [comment]
can anyone from the maintainers please check, there is some spelling mistake in the CHANGLOG.md, as test is failed on that file

**Comment by swangi-kumari** [comment]
Hey @HeetVekariya ,
Please don't worry about that it wont block your PR to get merge.

**Review by SamraatBansal — APPROVED** [review]
LGTM

**Review by ArjunKarthik — APPROVED** [review]

**Comment by HeetVekariya** [comment]
Thank you for merging 🙂👍

**Comment by swangi-kumari** [comment]
Hey @HeetVekariya ,
Thanks a bunch for all your contributions! We’ve got a little something for you to show our appreciation.
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.
Thanks!

**Pull request merged**
