### PR TITLE
refactor(router): remove `WebhookApiErrorSwitch ` and implement error mapping using `ErrorSwitch`

### LINKED ISSUE #1326: [REFACTOR] Define the Mapping between `ConnectorError` and `ApiErrorResponse` using the `ErrorSwitch` trait
### Feature Description

Currently, we are mapping errors from `ConnectorError` to `ApiErrorResponse` using custom logic (can be found [here](https://github.com/juspay/hyperswitch/blob/cd0cf40fe29358700f92c1520475934752bb4b30/crates/router/src/core/webhooks/utils.rs#L52)).

We want to refactor this implementation to make use of the existing `ErrorSwitch` trait which satisfies the same usecase.

### Possible Implementation

We have a custom trait for conversion of error from `ConnectorError` to `ApiErrorResponse` as can be found using the link in the description above. The mapping has to be defined using the `ErrorSwitch` trait instead, and the custom trait can hence be deleted.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by PanGan21**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Refactor error mapping with WebhookApiErrorSwitch to make use of the existing `ErrorSwitch` trait which satisfies the same usecase.
Closes #1326

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by PanGan21** [comment]
[This](let dispute_details = connector.get_dispute_details(request_details).switch()?;) line would give an error `type annotations needed` which is not fixed if I add the type

**Comment by vspecky** [comment]
@PanGan21 Hey, you need to bring the `common_utils::errors::ReportSwitchExt` trait into scope to use `switch()` there. `impl ErrorSwitch<U> for T` provides the `T => U` conversion logic, but we need additional functionality to promote this logic to support `Result<R, error_stack::Report<T>> => Result<R, error_stack::Report<U>>`. The `ReportSwitchExt` trait and a corresponding impl imparts this functionality to all such Result types.
https://github.com/juspay/hyperswitch/blob/05ea08bcc5c69e09462a4019830170dc0f67dfd9/crates/common_utils/src/errors.rs#L79

**Comment by PanGan21** [comment]
> @PanGan21 Hey, you need to bring the `common_utils::errors::ReportSwitchExt` trait into scope to use `switch()` there. `impl ErrorSwitch<U> for T` provides the `T => U` conversion logic, but we need additional functionality to promote this logic to support `Result<R, error_stack::Report<T>> => Result<R, error_stack::Report<U>>` (which is what `get_dispute_details()` returns and what `disputes_incoming_webhook_flow()` is expecting to be returned). The `ReportSwitchExt` trait and a corresponding impl imparts this functionality to all such Result types.
> 
> https://github.com/juspay/hyperswitch/blob/05ea08bcc5c69e09462a4019830170dc0f67dfd9/crates/common_utils/src/errors.rs#L79

It indeed did the trick! Thanks for the help and the insights. I will publish the pr then 😃

**Review by vspecky — DISMISSED** [review]

**Review by SanchithHegde — DISMISSED** [review]

**Comment by SanchithHegde** [comment]
Thanks for the PR @PanGan21!

**Pull request merged**
