### PR TITLE
feat(core): Make cache configuration configurable at runtime

### PR DESCRIPTION
**Pull request by tusharxoxoxo**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context
#3276

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by tusharxoxoxo** [comment]
1. I think I should also change the values in `crates/storage_impl/src/reddis/cache.rs` but it is throwing an error whenever I try to change it, can someone guide me on how this could be done

2. My LSP is showing this error, even when I haven't made any changes to the code base
image

**Comment by tusharxoxoxo** [comment]
@dracarys18

**Comment by dracarys18** [comment]
Can you run
```
cargo c 
```
and check the error

**Comment by dracarys18** [comment]
Regarding change this in `cache.rs`, since this is a static we can't make it completely runtime configurable. Instead you can make consts like `MAX_CAPACITY` a static, You can refer https://github.com/juspay/hyperswitch/blob/5ad3f8939afafce3eec39704dcaa92270b384dcd/crates/external_services/src/kms.rs#L22 . This is ideally how we should do it

**Comment by tusharxoxoxo** [comment]
I will change my PR according to the way u mentioned above

**Comment by tusharxoxoxo** [comment]
in issue #3276, max_capacity was taken u32 but when it's used in `crates/storage_impl/src/reddis/cache.rs` it is u64, should I leave it as it is or make changes to it, either make both of them u64?
image
image

`const MAX_CAPACITY: u64 = 30;`
is already declared static in cache.rs at the top

**Comment by dracarys18** [comment]
> in issue #3276, max_capacity was taken u32 but when it's used in `crates/storage_impl/src/reddis/cache.rs` it is u64, should I leave it as it is or make changes to it, either make both of them u64? image image
> 
> `const MAX_CAPACITY: u64 = 30;` is already declared static in cache.rs at the top

You can keep it u64 as moka internally want you to pass this type in max_capacity

**Pull request closed without merging**
