### PR TITLE
fix(multitenancy): consistently use tenant nomenclature everywhere

### PR DESCRIPTION
**Pull request by dracarys18**
## Type of Change

- [x] Enhancement

## Description

This fixes the inconsistent nomenclature used for tenants in router and drainer code

### Additional Changes
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

This will eradicate confusion between `name` and `tenant_id` names in the tenant config. In the config below
`public = { base_url = "http://localhost:8080/", schema = "public", redis_key_prefix = "", clickhouse_database = "default"}`

The key `public` will be the tenant_id. This PR adds a custom deserializer for this part

## How did you test it?

**This cannot be tested on sandbox without enabling Multi Tenancy**

1. Application runs with the changed config and so does drainer
2. Do a request with  a valid `x-tenant-id` 

```bash
curl --location 'http://localhost:8080/accounts' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-tenant-id: public' \
--header 'api-key: test_admin' \
--data-raw '{
  "merchant_id": "1729601216",
  "locker_id": "m0010",
  "merchant_name": "NewAge Retailer",
  "merchant_details": {
    "primary_contact_person": "John Test",
    "primary_email": "JohnTest@test.com",
    "primary_phone": "sunt laborum",
    "secondary_contact_person": "John Test2",
    "secondary_email": "JohnTest2@test.com",
    "secondary_phone": "cillum do dolor id",
    "website": "www.example.com",
    "about_business": "Online Retail with a wide selection of organic products for North America",
    "address": {
      "line1": "1467",
      "line2": "Harrison Street",
      "line3": "Harrison Street",
      "city": "San Fransico",
      "state": "California",
      "zip": "94122",
      "country": "US"
    }
  },
  "return_url": "https://google.com/success",
  "webhook_details": {
    "webhook_version": "1.0.1",
    "webhook_username": "ekart_retail",
    "webhook_password": "password_ekart@123",
    "payment_created_enabled": true,
    "payment_succeeded_enabled": true,
    "payment_failed_enabled": true
  },
  "sub_merchants_enabled": false,
  "metadata": {
    "city": "NY",
    "unit": "245"
  },
  "primary_business_details": [
    {
      "country": "US",
      "business": "default"
    }
  ]
}'
```
It should return 200 and `tenant-id` should be the which has been passed

3. Try the request with invalid `tenant-id`, It should return an error

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

### CODE REVIEW

**Review by jagan-jaya — DISMISSED** [review]

**Review by apoorvdixit88 — COMMENTED** [review]
Can we _please_ update following as well?
- `evn_specific.toml`
- `config.example.toml`

Also we have to make corresponding config changes in Cloud as well?

**Review by Chethan-rao — DISMISSED** [review]

**Comment by dracarys18** [comment]
Done @apoorvdixit88

**Review by apoorvdixit88 — APPROVED** [review]

**Review by jagan-jaya — DISMISSED** [review]

**Review by jarnura — APPROVED** [review]

**Comment by SanchithHegde** [comment]
Not a blocker, can you also update the tenant ID being logged in the middleware?

https://github.com/juspay/hyperswitch/blob/829a20cc933267551e49565d06eb08e03e5f13bb/crates/router/src/middleware.rs#L169

**Comment by apoorvdixit88** [comment]
> Not a blocker, can you also update the tenant ID being logged in the middleware?
> 
> https://github.com/juspay/hyperswitch/blob/829a20cc933267551e49565d06eb08e03e5f13bb/crates/router/src/middleware.rs#L169

@SanchithHegde I will cover this is my upcoming PRs related to tenancy. If this works?

**Comment by dracarys18** [comment]
> [hyperswitch/crates/router/src/middleware.rs](https://github.com/juspay/hyperswitch/blob/829a20cc933267551e49565d06eb08e03e5f13bb/crates/router/src/middleware.rs#L169)
> 
> Line 169 in [829a20c](/juspay/hyperswitch/commit/829a20cc933267551e49565d06eb08e03e5f13bb)

Have fixed this

**Review by SanchithHegde — DISMISSED** [review]

**Review by apoorvdixit88 — DISMISSED** [review]

**Review by Chethan-rao — DISMISSED** [review]

**Review by jagan-jaya — APPROVED** [review]

**Review by apoorvdixit88 — APPROVED** [review]

**Review by Chethan-rao — APPROVED** [review]

**Review by jarnura — APPROVED** [review]

**Review by SanchithHegde — APPROVED** [review]

**Pull request merged**
