### PR TITLE
chore: drop `temp_card` table and all associated items

### PR DESCRIPTION
**Pull request by SanchithHegde**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

This PR removes the `temp_card` table and all associated queries, functions, etc.

### Additional Changes

- [x] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

**Database Changes:**

- The `temp_card` table has been dropped. The `up.sql` and `down.sql` files just have queries related to the `temp_card` table from the `down.sql` and `up.sql` files in the [`2022-09-29-084920_create_initial_tables`](https://github.com/juspay/hyperswitch/tree/ba5c3efc867c983bed6acf249f2cf55af4fda08b/migrations/2022-09-29-084920_create_initial_tables) directory, respectively.

**Configuration Changes:**

- The `aws_key_id`, `aws_region` and `temp_card_key` fields have been removed from the `Keys` struct (`[keys]` table in the TOML files).
- The `keys` field(`[keys]` table) has been renamed to `secrets`, since it no longer holds any keys.

## Motivation and Context

Cleaning up unused code.

## How did you test it?

N/A

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by SanchithHegde** [comment]
By the way, [`services::encrypt()`](https://github.com/juspay/hyperswitch/blob/c60029bf12b4629f6cd1c18d82351256ac2b1264/crates/router/src/services/encryption.rs#L118) and [`services::decrypt()`](https://github.com/juspay/hyperswitch/blob/c60029bf12b4629f6cd1c18d82351256ac2b1264/crates/router/src/services/encryption.rs#L141) seem to be unused. Should we keep them for now?

**Comment by manoj-juspay** [comment]
> 
No , keep these in case we want to keep data that needs to encrypted and kept in the database

**Comment by manoj-juspay** [comment]
LGTM

**Review by manoj-juspay — APPROVED** [review]
LGTM

**Review by jarnura — APPROVED** [review]

**Pull request merged**
