### PR TITLE
feat(connector): [Worldpay] Use connector_request_reference_id as reference to the connector

### PR DESCRIPTION
**Pull request by ayan-joshi**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

As mentioned in the issue #2321 , I had to work on the attempt_id and payment_id in the Router data , it should have been replaced with the new introduced connector_request_reference_id.
I think I have did it.

please have a look and merge if it's done @VedantKhairnar @srujanchikke 

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by prasunna09** [comment]
Hi @ayan-joshi , Please follow [commit message guidelines ](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md#commit-message-guidelines)and

Please use `cargo +nightly fmt` to fix the failing formatting check

**Comment by ayan-joshi** [comment]
@prasunna09 what's the issue with pr title ?
And I have made changes have a look now formatting is being changed

**Comment by ayan-joshi** [comment]
@prasunna09 is it okay

**Comment by SanchithHegde** [comment]
@ayan-joshi Could you resolve the merge conflicts?

**Comment by ayan-joshi** [comment]
> @ayan-joshi Could you resolve the merge conflicts?

I am not getting what's with it , as described in the issue I just changed the attempt_id to connector_request_reference_id
why it's getting conflicted

**Comment by SanchithHegde** [comment]
> > @ayan-joshi Could you resolve the merge conflicts?
> 
> I am not getting what's with it , as described in the issue I just changed the attempt_id to connector_request_reference_id why it's getting conflicted

You're seeing merge conflicts here because a subset of lines in the same file were modified by both you and another PR that landed on our `main` branch.

**Comment by ayan-joshi** [comment]
@SanchithHegde I don't have permissions from the main branch , how could i resolve the conflicts any maintainer would need to accept one

**Comment by SanchithHegde** [comment]
> I don't have permissions from the main branch , how could i resolve the conflicts any maintainer would need to accept one

You can click on the "Resolve conflicts" button that the GitHub UI shows and include changes that are relevant to your PR, it would then commit the changes to your branch itself, which you have access to commit and push to.

**Comment by ayan-joshi** [comment]
> > I don't have permissions from the main branch , how could i resolve the conflicts any maintainer would need to accept one
> 
> You can click on the "Resolve conflicts" button that the GitHub UI shows and include changes that are relevant to your PR, it would then commit the changes to your branch itself, which you have access to commit and push to.

I did it but it's not getting change , I have done the commit twice on my branch @SanchithHegde

**Comment by ayan-joshi** [comment]
@SanchithHegde @srujanchikke All checks have been passed , can u merge the pr ?

**Review by srujanchikke — APPROVED** [review]
LGTM!

**Review by SanchithHegde — APPROVED** [review]
Looks good to me!

Thanks for the PR, @ayan-joshi!

**Comment by swangi-kumari** [comment]
Hey @ayan-joshi ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!

**Pull request merged**
