### PR TITLE
fix(refunds): remove to schema from refund aggregate response and exclude it from open api documentation

### PR DESCRIPTION
**Pull request by qstommyshu**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Removed all the openapi references to `RefundAggregateResponse`.

1. Removed `ToSchema` trait for `RefundAggregateResponse`.
2. Removed references from `openapi` and `openapi_v2` to `RefundAggregateResponse`.
3. Generated new `openapi_spec` file based on the above changes.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

#5990

## How did you test it?

Tested manually.
The references of `RefundAggregateResponse` is removed in openapi generated  json file after the modification.
image

image

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Comment by qstommyshu** [comment]
Hi @apoorvdixit88 ,

I've removed all the openapi references (both v1 and v2) to `RefundAggregateResponse`. However, I don't see any differences in the generated openapi documents. It seems `RefundAggregateResponse` is not displayed even though openapi document has reference to it.

**Comment by apoorvdixit88** [comment]
> Hi @apoorvdixit88 ,
> 
> I've removed all the openapi references (both v1 and v2) to `RefundAggregateResponse`. However, I don't see any differences in the generated openapi documents. It seems `RefundAggregateResponse` is not displayed originally even though openapi document has reference to it.

Hi @qstommyshu 
We can see the openapi documents changes in the files.
Also there is some conflict, can you please check?

**Comment by qstommyshu** [comment]
> > Hi @apoorvdixit88 ,
> > I've removed all the openapi references (both v1 and v2) to `RefundAggregateResponse`. However, I don't see any differences in the generated openapi documents. It seems `RefundAggregateResponse` is not displayed originally even though openapi document has reference to it.
> 
> Hi @qstommyshu We can see the openapi documents changes in the files. Also there is some conflict, can you please check?

I pulled out the generated openapi documents but didn't see anything different for some reason...

**Review by apoorvdixit88 — APPROVED** [review]

**Review by dracarys18 — APPROVED** [review]

**Comment by Gnanasundari24** [comment]
@qstommyshu Please add the proper description and testcases

**Comment by apoorvdixit88** [comment]
> @qstommyshu Please add the proper description and testcases

HI @qstommyshu Please add description as well.

**Comment by likhinbopanna** [comment]
@apoorvdixit88 Can you add the test cases ?

**Comment by qstommyshu** [comment]
> @apoorvdixit88 Can you add the test cases ?

Humm, I'm not sure what other test cases I can add. According to this comment, I think the test case I currently have is proper test cases? 

> > Hi @apoorvdixit88 ,
> > I've removed all the openapi references (both v1 and v2) to `RefundAggregateResponse`. However, I don't see any differences in the generated openapi documents. It seems `RefundAggregateResponse` is not displayed originally even though openapi document has reference to it.
> 
> Hi @qstommyshu We can see the openapi documents changes in the files. Also there is some conflict, can you please check?

Correct me if I'm wrong.

**Pull request merged**
