### PR TITLE
fix(event): Updated the ApiEventMetric

### LINKED ISSUE #5059: bug(events): update the ApiEventsType for `PaymentsSessionResponse` to use payments flow
update the `ApiEventMetric` trait for this response to return `ApiEventsType::Payment { payment_id : String}` variant.
based on the payment id stored in its body

This would help for better structuring and help list this api call in the dashboard events as well

### PR DESCRIPTION
**Pull request by tanbirali**
## Type of Change

- [x] Bugfix

## Description

Updated the `ApiEventMetric` trait to return `ApiEventsType::Payment { payment_id : String}` variant.
Fixes #5059 

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I reviewed the submitted code

### CODE REVIEW

**Comment by lsampras** [comment]
Hey @tanbirali 
you'll need to update the `ApiEventMetric` trait implementation for `PaymentsSessionResponse` which is defined [here](https://github.com/juspay/hyperswitch/blob/86f4060d332b3515a92010287be32fe69508d451/crates/api_models/src/events.rs#L43)

you can refer to this implementation 
https://github.com/juspay/hyperswitch/blob/86f4060d332b3515a92010287be32fe69508d451/crates/api_models/src/events/payment.rs#L48-L54

**Comment by tanbirali** [comment]
Let me know if I got this right this time

**Comment by lsampras** [comment]
yup,
can you move it to this file `crates/api_models/src/events/payment.rs`.
and remove the older implementation [here](https://github.com/juspay/hyperswitch/blob/86f4060d332b3515a92010287be32fe69508d451/crates/api_models/src/events.rs#L43)

**Comment by tanbirali** [comment]
` crates/api_models/src/events/payment.rs`  file has  this already implemented and when I add `payment_id` field, there I am getting no such field exists

**Comment by tanbirali** [comment]
Let me know if I need to do anything else

**Comment by lsampras** [comment]
Hey @tanbirali, you'll need to remove this line I think since it causes duplicate implementations of this trait
https://github.com/juspay/hyperswitch/blob/86f4060d332b3515a92010287be32fe69508d451/crates/api_models/src/events.rs#L43

**Comment by lsampras** [comment]
Can you also add screenshots for local testing?

you can run the data pipeline and this event should show up in the dashboard events & logs section when you make an sessions api call.

**Comment by tanbirali** [comment]
Sorry I can't do the local testing right now I had issues setting it up with docker, hyperswitch server was failing, I had a talk with @SanchithHegde about this, if I can I will add a ss of the local test

**Review by lsampras — DISMISSED** [review]

**Review by SanchithHegde — DISMISSED** [review]

**Comment by lsampras** [comment]
@tanbirali Would you be able to fix the CI failures here?

**Comment by tanbirali** [comment]
Let me give it a try

**Comment by tanbirali** [comment]
@lsampras All done I guess

**Review by SanchithHegde — APPROVED** [review]

**Review by lsampras — APPROVED** [review]

**Pull request merged**
