### PR TITLE
feat(connector): [Payeezy] Use connector_response_reference_id as reference to merchant

### LINKED ISSUE #2312: [FEATURE]: [Payeezy] Use `connector_request_reference_id` as reference to the connector
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### LINKED ISSUE #2343: [FEATURE]: [Payeezy] Use `connector_response_reference_id` as reference to merchant
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by rootCircle**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add `connector_response_reference_id` support for Payeezy
- Used `transaction_id` as the reference id, while implementing this!  

Resolves #2343 and resolves #2312.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## How did you test it?

Need help testing!

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by srujanchikke — APPROVED** [review]
Looks good to me!

**Review by SanchithHegde — APPROVED** [review]
Looks good to me!

Thanks for the PR, @rootCircle!

**Comment by rootCircle** [comment]
Thanks :-)

**Comment by VedantKhairnar** [comment]
Hey @rootCircle  :wave:,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.
Thanks!

**Comment by rootCircle** [comment]
Sure! Thanks a lot! :smile:

**Comment by shakeel-3** [comment]
Hi @rootCircle ,

I hope this message finds you well. My name is Mohd Shakeel, and I'm currently working on an issue in GitHub that is quite similar to one you successfully resolved #2343 and #2312 .

I've been trying to address this issue #2311 , but I've hit a roadblock and could use some guidance. Since you've already successfully tackled a similar problem, I was wondering if you could spare a moment to share your approach or any insights that might help me make progress.

I truly appreciate any assistance you can provide, and I understand that you might be busy. If you have the time, even a brief overview of how you approached the issue would be immensely helpful.

Thank you in advance for considering my request, and I look forward to hearing from you. Your expertise would be invaluable in helping me move forward with this problem.

Best regards,
Mohd Shakeel

**Comment by rootCircle** [comment]
Sure! @shakeel-3, can you explain what problem you're facing? 

Heading over this, this PR might be a good way to start, https://github.com/juspay/hyperswitch/pull/2052. (See the file changes to get an idea)
If you're facing any problem related to rust, head over to [the book](https://doc.rust-lang.org/book/) or [this](https://fasterthanli.me/articles/a-half-hour-to-learn-rust).
If you're facing problem related to OpenNode, then I recommend spending some time with official docs of OpenNode API.

Side-note : You can also join the Discord/Slack Server to get more personalized help!(you can ping me there too! :-)) (Discussing here might unnecessarily ping the maintainers)

**Comment by Sakilmostak** [comment]
Hello @shakeel-3 , for any further help you can hit our official [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) or [discord](https://discord.com/invite/wJZ7DVW8mm) server. We will be happy to help you :)

**Pull request merged**
