### PR TITLE
refactor(router): removed unused function for merchant connector account

### LINKED ISSUE #1998: [REFACTOR] remove unused function for merchant connector account
The function `find_merchant_connector_account_by_merchant_id_connector_name` which was used to query the merchant connector account ( stripe, adyen etc ) is no longer needed. This can be removed safely. Remove all the child functions and ensure that the project compiles. https://github.com/juspay/hyperswitch/blob/f0cc0fba1684f200ce6dbf3e4bc951de23a60f94/crates/router/src/db/merchant_connector_account.rs#L214

### PR DESCRIPTION
**Pull request by heysharan**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR removes the function and child functions of `find_merchant_connector_account_by_merchant_id_connector_namechild` in `hyperswitch/crates/router/src/db/merchant_connector_account.rs` and the project compiled successfully 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Closes #1998

## How did you test it?

Screenshot 2023-11-01 at 5 11 10 PM

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by heysharan** [comment]
hey @SanchithHegde, can you please assign me to #1998.

**Comment by SanchithHegde** [comment]
@heysharan How about this, we wait 2-3 more days for the current assignee to respond, so that they would have had a week to respond? And if they don't, we can assign it to you.

Also, please comment on the issue itself (after 2 or 3 days). GitHub has a restriction that we can't assign an issue to someone outside the organization unless they comment on the issue.

**Comment by heysharan** [comment]
@SanchithHegde Sure, Thank you

**Comment by heysharan** [comment]
Hey @SanchithHegde I have compiled the project without any warnings, please review it.

**Comment by SanchithHegde** [comment]
Closing this as discussed in https://github.com/juspay/hyperswitch/issues/1998#issuecomment-1818277627.

**Pull request closed without merging**
