### PR TITLE
refactor(cards,router): Remove duplicated card number interface

### LINKED ISSUE #4442: Remove duplicated card number interface
### Feature Description

The CardNumber interface has a duplicated method with the same functionality.

### Possible Implementation

Remove one of the duplicated interfaces.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by yongjoon-km**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

The CardNumber interface has a duplicated method with the same functionality. Removed one.
closes #4442
### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

1. crates/cards/src/validate
2. crates/router/src/core/blocklist/utils

## How did you test it?

The methods get_extended_card_bin() and get_card_extended_bin() are identical and thus redundant. It is recommended to keep one and remove the other to avoid confusion.

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by vspecky — CHANGES_REQUESTED** [review]
Hey @yongjoon-km, thanks for the PR!

Can you remove the `get_card_extended_bin()` function instead (keep `get_extended_card_bin()`). This is to ensure consistent naming of the `extended card bin` across the codebase.

**Comment by yongjoon-km** [comment]
> Hey @yongjoon-km, thanks for the PR!
> 
> Can you remove the `get_card_extended_bin()` function instead (keep `get_extended_card_bin()`). This is to ensure consistent naming of the `extended card bin` across the codebase.

I will change to use `get_extended_card_bin()` instead of `get_card_extended_bin()` Thanks for your feedback.

**Review by vspecky — DISMISSED** [review]
@yongjoon-km LGTM! Please create and link an Issue to fix the failing CI check.

**Review by SanchithHegde — DISMISSED** [review]

**Comment by SanchithHegde** [comment]
Hey @yongjoon-km, just so you're aware, you don't need to repetitively merge `main` branch into your PR, the merge queue will handle that for you.

**Review by Narayanbhat166 — APPROVED** [review]

**Comment by yongjoon-km** [comment]
> Hey @yongjoon-km, just so you're aware, you don't need to repetitively merge `main` branch into your PR, the merge queue will handle that for you.

Oh.. I didn't know that. Thank you.

**Review by SanchithHegde — APPROVED** [review]

**Review by Narayanbhat166 — APPROVED** [review]

**Pull request merged**
