### PR TITLE
feat: Add amount to Signifyd

### PR DESCRIPTION
**Pull request by adi-kmt**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

This PR solves issue #6119

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Comment by adi-kmt** [comment]
@pixincreate @ThisIsMani There seems to be many trait implementations absent in signifyd and also no tests implemented.
Should that be done in this PR?

**Comment by pixincreate** [comment]
> @pixincreate @ThisIsMani There seems to be many trait implementations absent in signifyd and also no tests implemented. Should that be done in this PR?

no.

tagging relevant person for this for detailed clarification: @swangi-kumari

**Comment by awasthi21** [comment]
Hi @adi-kmt 
Please run these 
```
cargo +nightly fmt --all
cargo clippy
```
and resolve the CI Checks Error
Screenshot 2024-10-14 at 12 40 41 PM



Also you will have to make amount changes here too 
```juspay/hyperswitch/crates/router/src/connector/signifyd/transformers/api.rs```

**Review by awasthi21 — CHANGES_REQUESTED** [review]
Add amount conversion changes in 
`juspay/hyperswitch/crates/router/src/connector/signifyd/transformers/api.rs` file too

**Pull request closed without merging**
