### PR TITLE
refactor(worldline): use `connector_request_reference_id` as reference to the connector

### LINKED ISSUE #2320: [FEATURE]: [Worldline] Use `connector_request_reference_id` as reference to the connector
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by PanGan21**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Replace `payment_id` with `connector_request_reference_id` in worldline.
Closes #2320 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by prasunna09 — COMMENTED** [review]
@PanGan21  Could you please go through the issue once again. The changes that you made are not expected . Please let us know if you need any help in understanding the problem .

**Comment by PanGan21** [comment]
> @PanGan21 Could you please go through the issue once again. The changes that you made are not expected . Please let us know if you need any help in understanding the problem .

Thanks for checking. I was trying to compare it with #2052
In the `worldline/transformers.rs` I couldn't find any reference to `attempt_id` or `payment_id` which are described in the issue.
I can only see usage of `connector_response_reference_id` and `resource_id`. Are these two vars related to this issue?

**Comment by PanGan21** [comment]
> @PanGan21 Could you please go through the issue once again. The changes that you made are not expected . Please let us know if you need any help in understanding the problem .

Thanks for checking. I was trying to compare it with #2052
I changed `connector_response_reference_id` to use `connector_request_reference_id` instead. Let me know if that was meant from the issue or I misunderstood it

**Comment by srujanchikke** [comment]
> > @PanGan21 Could you please go through the issue once again. The changes that you made are not expected . Please let us know if you need any help in understanding the problem .
> 
> Thanks for checking. I was trying to compare it with #2052 I changed `connector_response_reference_id` to use `connector_request_reference_id` instead. Let me know if that was meant from the issue or I misunderstood it

Hi @PanGan21 ,

The issue mentions that merchant reference id field from connector request(need to check in [world line documentation](https://apireference.connect.worldline-solutions.com/s2sapi/v1/en_US/java/payments/create.html?paymentPlatform=ALL) ) should be set to `connector_request_reference_id` . Please let us know if you have any other queries

**Review by srujanchikke — APPROVED** [review]
Looks good to me!

**Review by SanchithHegde — APPROVED** [review]
Looks good to me!

Thanks for the PR, @PanGan21!

**Comment by VedantKhairnar** [comment]
Hey @PanGan21  👋,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.
Thanks!

**Pull request merged**
