### PR TITLE
refactor(connector): [Payme] Remove Default Case Handling

### LINKED ISSUE #2282: [REFACTOR]: [Payme] Remove Default Case Handling
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Rutam21**
## Type of Change

- [x] Refactoring

## Description

This PR removes the default case handling and adds error handling for all the available cases.

Fixes #2282 

## How did you test it?

No test cases. As In this PR only error message have been populated for all default cases.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

### CODE REVIEW

**Comment by Rutam21** [comment]
Please review and suggest changes, if any. Thanks.

cc: @SamraatBansal @Sangamesh26 @ArjunKarthik

**Comment by swangi-kumari** [comment]
Hey @Rutam21 ,
Please comment on the issue [2282](https://github.com/juspay/hyperswitch/issues/2282), so that we can assign that issue to you.

**Review by swangi-kumari — APPROVED** [review]

**Review by AkshayaFoiger — APPROVED** [review]

**Review by Gnanasundari24 — APPROVED** [review]

**Review by SanchithHegde — APPROVED** [review]
Looks good to me!

Thanks for the PR, @Rutam21!

**Comment by deepanshu-iiitu** [comment]
Hey @Rutam21  ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!

**Pull request merged**
