### PR TITLE
feat:Payments cancellation can now be authenticated using publishable key

### PR DESCRIPTION
**Pull request by prajjwalkumar17**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
We weren't able to use publishable key as authentication for the payments cancel. So the publishable key auth is required for the authentication type of cancel payment. We will require the publishable key auth and moreover we will require to add the client_secret in the body of the cancel payment.

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
We are implementing the same authentication as was present in the confirm payments

## How did you test it?
tested it manually using PM.
Screenshot 2023-05-02 at 17 33 50

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by Abhicodes-crypto** [comment]
If publishable key auth is enabled for cancel API. Then customer can cancel the payment after `Authorizing`. I don't think this is a desirable feature and only the merchant should be able to cancel the payment. As far as I know payment gateways like stripe also don't support cancelling payments using publishable keys.

**Comment by prajjwalkumar17** [comment]
@Abhicodes-crypto I have added you to the thread in slack where this feature is being discussed

**Comment by Abhicodes-crypto** [comment]
> Moreover we aren't sending the request to connector

@prajjwalkumar17 , afaik if the payment is in `requires_capture` state then request is sent to connector to cancel the payment. But for other status connector is not called.

**Comment by prajjwalkumar17** [comment]
@Abhicodes-crypto Yeah so for that status we already have the cancel payments implemented and for the other statuses we have mentioned we are creating our own check methods that what I have done.

**Comment by Narayanbhat166** [comment]
> If publishable key auth is enabled for cancel API, then customer can cancel the payment after `Authorizing`. I don't think this is a desirable feature and only the merchant should be able to cancel the payment. As far as I know payment gateways like stripe also don't support cancelling payments using publishable keys.

cc @bernard-eugine. @Abhicodes-crypto is right, should we allow this?

**Review by jarnura — APPROVED** [review]

**Review by jarnura — COMMENTED** [review]
Currently Payments cancellation only available for auth and capture payments.

For non auth and capture payments, via SDK we don't want to allow the cancellation.

There are auto expiry logic's to handle the same.

For payment links and user cancellation features we might need this, but while implementing the feature we need to revamp the solution.

**Pull request closed without merging**
