### PR TITLE
refactor(router): remove unnecessary function from Refunds Validate Flow

### PR DESCRIPTION
**Pull request by AaronTJDev**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Refactoring to remove `validate_uniqueness_of_refund_id_against_merchant_id` as it isn't required because of the db being a unique btree. So you are able to try to insert the refund by id and if the insert fails then the refund is not valid . 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

#1521 

## How did you test it?

Tested by:

1. Creating a stripe payment
2. Creating a refund using the payment id successfully.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by SanchithHegde** [comment]
@AaronTJDev Could you address the failing CI checks?

**Comment by AaronTJDev** [comment]
@SanchithHegde Apologies, my rust-analyzer plugin didn't catch that error due to some caching issues locally! This is updated now.

**Review by Abhicodes-crypto — APPROVED** [review]

**Review by SanchithHegde — APPROVED** [review]
Looks good to me!

Thanks for the PR, @AaronTJDev!

**Comment by swangi-kumari** [comment]
Hello @AaronTJDev ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!

**Comment by AaronTJDev** [comment]
Hi @swangi-kumari, thank you for your kindness! However, I've already signed up previously (see link below). Thank you for providing an awesome experience for contributors.

https://github.com/juspay/hyperswitch/pull/2456#issuecomment-1750534969

**Pull request merged**
