### PR TITLE
feat(multitenancy): move users and tenants to global schema

### PR DESCRIPTION
**Pull request by jagan-jaya**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Users will be global and not tied to a tenant
Login page will be one and not customized. An option to switch tenants will be provided

https://github.com/juspay/hyperswitch-product/issues/50

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

To establish tenancy in our application and start using the default tenant as 'Hyperswitch' and also offer a 'test' tenant in all environments

Users will be global and not tied to a tenant
Login page will be one and not customized. An option to switch tenants will be provided

## How did you test it?

1. Start router and control center and try creating new user account.
2. Check if the user is getting created and an entry added in public schema for the user
3. Try sign out from the control center and login again
4. Login should work as expected

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Review by jarnura — DISMISSED** [review]
LGTM

**Review by racnan — COMMENTED** [review]
You can remove the join query if it wont be used and wont work if used.

**Review by jarnura — APPROVED** [review]

**Review by lsampras — APPROVED** [review]
the analytics/reporting changes look good

**Review by racnan — APPROVED** [review]
Join query not removed.

**Comment by jagan-jaya** [comment]
https://github.com/juspay/hyperswitch/pull/4781#pullrequestreview-2099085923
Will be fixed in [this PR ](https://github.com/juspay/hyperswitch/pull/4781)

**Pull request merged**
