### PR TITLE
refactor(connector): [Payeezy] update error message

### PR DESCRIPTION
**Pull request by HeetVekariya**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- Fix issue: #2856 
- Changes to be made: update the error message
- File changed: **```transformers.rs```** (crates/router/src/connector/payeezy/transformers.rs)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by swangi-kumari — APPROVED** [review]
LGTM!

**Comment by HeetVekariya** [comment]
@swangi-kumari Is there anything i need to do ?

**Comment by SanchithHegde** [comment]
@HeetVekariya Could you resolve the merge conflicts?

**Review by viniAOliver — COMMENTED** [review]
Good job

**Comment by HeetVekariya** [comment]
- @SanchithHegde To solve the merge conflicts i have to update my branch because it is 27 commits behind so, i have to reset my branch first and then fast-forward it. 
- So while doing this PR got close.
- But i have opened another PR #2919

**Pull request closed without merging**
