### PR TITLE
refactor(connector): [Paypal] Change error message from NotSupported to NotImplemented

### PR DESCRIPTION
**Pull request by parisosuch-dev**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Refactored `NotSupported` Error calls to `NotImplemented` in the Paypal transformer.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

Changes are here: `crates/router/src/connector/paypal/transformer.rs`

## Motivation and Context

These changes fix the open issue #2858.

## How did you test it?

Make any payment for Paypal connector for any PM which is not implemented, and see for the error message - it should be payment method not implemented

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by parisosuch-dev** [comment]
@swangi-kumari are you able to review my PR. I resolved the conflict.

**Comment by parisosuch-dev** [comment]
@swangi-kumari this PR should be ready to go

**Comment by parisosuch-dev** [comment]
@prasunna09 possibly review so I can close this out?

**Comment by parisosuch-dev** [comment]
> Hey @parisosuch-dev, Thanks for the PR and apologies for the delay. We would be happy to review it and get the PR merged.

Sounds good -- I reopened the PR.

**Comment by swangi-kumari** [comment]
Hey @parisosuch-dev ,
Please resolve the conflicts from your branch.

**Comment by VedantKhairnar** [comment]
Hey @parisosuch-dev ,
Let us know if you are facing any issues and need assistance in the merge conflicts. Happy to help : )

**Review by srujanchikke — APPROVED** [review]

**Review by ArjunKarthik — APPROVED** [review]

**Pull request merged**
