### PR TITLE
refactor(connector): Use connector_request_reference_id for rapyd

### LINKED ISSUE #2346: [FEATURE]: [Rapyd] Use `connector_response_reference_id` as reference to merchant
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- Please refer to the Rapyd API documentation [here](https://docs.rapyd.net/en/create-payment.html). In the payment response, there is a field called `merchant_reference_id` (an optional field). This `merchant_reference_id` needs to be mapped to the `connector_response_reference_id`.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by vinfinity7**
## Type of Change

Fixes #2346 
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by vinfinity7** [comment]
@srujanchikke Kindly review this too !

**Comment by srujanchikke** [comment]
Hi @vinfinity7 ,

The issue #2346 is not assigned to you, Please comment on the issue to get assigned it to you.

**Comment by vinfinity7** [comment]
image
update the field as given in the docs @srujanchikke

**Comment by srujanchikke** [comment]
> connector response reference id

Connector response reference id and connector request reference id are two different fields. Please go through the issue attached PR. This PR should be modifying response reference id not request reference id.

Please use following cargo commands -

cargo clippy --all-features
ref -[ Cargo commands](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md#cargo-commands), and fix the errors thrown by clippy for the checks to pass .

**Comment by vinfinity7** [comment]
@srujanchikke can you be more clear as to exaclty where is the response data being handled 
image
The last line has been added by me

**Comment by srujanchikke** [comment]
> @srujanchikke can you be more clear as to exaclty where is the response data being handled image The last line has been added by me

Yes, you're right. You need add it in ResponseData struct and map that to connector response reference id.
Screenshot 2024-03-18 at 1 18 14 PM

**Comment by vinfinity7** [comment]
@srujanchikke 
image
this shall work ?

**Comment by srujanchikke** [comment]
> @srujanchikke image this shall work ?

No this doesn't work, you are trying add field in transaction response, you need to map `connector_response_reference_id` to `merchant_reference_id`. which would be something like this

```
connector_response_reference_id: merchant_reference_id
```
and also you need to populate merchant_reference_id from connector response before mapping. Please go through this example [PR](https://github.com/juspay/hyperswitch/pull/1735/files) for more info. 

Please change the title of the PR to `connector_response_reference_id for rapyd`

**Pull request closed without merging**
