### PR TITLE
refactor(postman): Fix payme postman collection for handling `order_details`

### PR DESCRIPTION
**Pull request by sahkal**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Postman testcases for payme is failing due to orderDetails dependency on total amount

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## How did you test it?

image (2)
image (3)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by pixincreate** [comment]
- Please install Newman using: `npm install -g 'https://github.com/knutties/newman.git#feature/newman-dir'`  
- Export the connector auth
- Run `cargo run --package test_utils --bin test_utils -- --connector_name=<connector_name> --base_url=<base_url> --admin_api_key=<admin_api_key>`

For more info, please refer: https://github.com/juspay/hyperswitch/blob/main/crates/test_utils/README.md

**Comment by sahkal** [comment]
> * Please install Newman using: `npm install -g 'https://github.com/knutties/newman.git#feature/newman-dir'`
> * Export the connector auth
> * Run `cargo run --package test_utils --bin test_utils -- --connector_name=<connector_name> --base_url=<base_url> --admin_api_key=<admin_api_key>`
> 
> For more info, please refer: https://github.com/juspay/hyperswitch/blob/main/crates/test_utils/README.md
> 
> Once the tests are run, please attach the screenshots in the description
> 
> Also, check the deployment-readiness failing

VAS is not compiling due to some issue unrelated to my PR

**Review by likhinbopanna — APPROVED** [review]

**Comment by Gnanasundari24** [comment]
@sahkal Please add the screenshot for the test run

**Comment by sahkal** [comment]
> @sahkal Please add the screenshot for the test run

Few of the test cases are failing with error related to connector side issue, which is unrelated to the change i made.

**Review by Gnanasundari24 — APPROVED** [review]

**Pull request merged**
