### PR TITLE
feat(connector): [Bambora] use connector_request_reference_id

### PR DESCRIPTION
**Pull request by j-alder**
Addresses #2293

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR updates the use of `RequestData.request.connector_transaction_id` to `RequestData.connector_request_reference_id` for Bambora.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

This addresses issue #2293 by setting `connector_request_reference_id` on Bambora make payment responses.

## How did you test it?

I ensured compilation was successful and existing tests ran successfully after changes were applied.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by prasunna09 — CHANGES_REQUESTED** [review]
@j-alder Could you please go through the issue once again . The changes that you made are not expected . Please let us know if you need any help in understanding the problem .

**Comment by j-alder** [comment]
Thank you @prasunna09 - I was misunderstanding the issue. I reverted my previous changes and committed what I believe is the only change necessary for Bambora.

**Review by prasunna09 — CHANGES_REQUESTED** [review]
Hi @j-alder, the issue you have been assigned is related to connector_request_reference_id but this pr have changes related to connector_response_reference_id. Can you please go through the issue once again, please make changes accordingly.

**Comment by j-alder** [comment]
Thanks again @prasunna09, I've updated the request body struct to include the identifier laid out in the Bambora documentation and added the proper value in the implementation.

**Review by SanchithHegde — APPROVED** [review]
Looks good to me!

Thanks for the PR, @j-alder!

**Comment by swangi-kumari** [comment]
Hey @j-alder ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!

**Pull request merged**
