### PR TITLE
refactor: fix unit and documentation tests

### PR DESCRIPTION
**Pull request by SanchithHegde**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [x] CI/CD

## Description

This PR enables the usage of `sccache` for caching compilation artifacts in the CI-pr workflow, and fixes the existing unit and documentation tests. I'll be taking up running the unit and documentation on pull requests in a separate PR, with some more CI workflow improvments.

## Motivation and Context

Fixing unit tests so that they can be run as part of pull request checks.

## How did you test it?

I've run unit tests locally with the following command (with locally running Postgres and Redis servers), and they pass:

```shell
FEATURES=$(cargo metadata --all-features --format-version 1 | \
  jq -r '
    [ ( .workspace_members | sort ) as $package_ids # Store workspace crate package IDs in `package_ids` array
    | .packages[] | select( IN(.id; $package_ids[]) ) | .features | keys[] ] | unique # Select all unique features from all workspace crates
    | del( .[] | select( any( . ; . == ("aws_kms", "aws_s3", "release", "vergen") ) ) ) # Exclude some features from features list
    | join(",") # Construct a comma-separated string of features for passing to `cargo`
  ')
cargo nextest run --config-file .github/nextest.toml --profile ci -E 'kind(lib)' --features "${FEATURES}" --status-level none
```

Screenshot of nextest run

Further, running documentation tests using the following command succeeds:

```shell
cargo test --doc --features "${FEATURES}"
```

I'm unable to include a screenshot of the documentation test run, since the output is too long.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [x] I added unit tests for my changes where possible

### CODE REVIEW

**Review by pixincreate — DISMISSED** [review]
CI changes, LGTM.

**Review by prajjwalkumar17 — DISMISSED** [review]

**Comment by prajjwalkumar17** [comment]
Approved on behalf of routing.

**Comment by SanchithHegde** [comment]
I've rebased the PR on a recent `main` branch, updated the PR to only fix unit and documentation tests, and enabled the use of `sccache` in the `CI-pr` workflow. I'll be adding the unit and documentation tests in a separate PR, possibly as a separate job, once I figure out the arguments that we would pass to `cargo nextest`. I've updated the PR description to reflect the same.

**Review by pixincreate — APPROVED** [review]
CI stuff, LGTM!

**Review by Narayanbhat166 — APPROVED** [review]

**Review by srujanchikke — APPROVED** [review]

**Pull request merged**
