### PR TITLE
feat(payments): Add audit events for PaymentCreate update

### LINKED ISSUE #4672: Add audit events for PaymentCreate update
Created from https://github.com/juspay/hyperswitch/issues/4525

This covers adding events for PaymentCreate operation

This event should include the payment data similar to https://github.com/juspay/hyperswitch/pull/4166

It should also include any metadata for the event
e.g reason for payment rejection, error codes, rejection source etc

### PR DESCRIPTION
**Pull request by Rutam21**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR adds an Audit event for the PaymentCreate operation.

### Additional Changes

- [x] This PR modifies the files below

- `crates/router/src/core/payments/operations/payment_create.rs`
- `crates/router/src/events/audit_events.rs`

## Motivation and Context

This PR fixes #4672 

## How did you test it

Hit the `Payments - Create` endpoint with `"confirm": false`
- Curl:
```bash
curl --location 'http://localhost:8080/payments' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: dev_LZcIA7XeMpnK5satp4CDvjcnHCaeKTBcosyuBBJaknZu1odhFo96cwS0nSdfzuJF' \
--data-raw '{
    "amount": 6540,
    "currency": "USD",
    "confirm": false,
    "capture_method": "automatic",
    "capture_on": "2022-09-10T10:11:12Z",
    "amount_to_capture": 6540,
    "customer_id": "StripeCustomer",
    "email": "guest@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "description": "Its my first payment request",
    "authentication_type": "no_three_ds",
    "return_url": "https://google.com",
    "payment_method": "card",
    "payment_method_type": "credit",
    "payment_method_data": {
        "card": {
            "card_number": "4242424242424242",
            "card_exp_month": "10",
            "card_exp_year": "25",
            "card_holder_name": "joseph Doe",
            "card_cvc": "123"
        }
    },
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "US",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "shipping": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "US",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "metadata": {
        "udf1": "value1",
        "new_customer": "true",
        "login_date": "2019-09-10T10:11:12Z"
    },
    "profile_id": "pro_v5sFoHe80OeiUlIonocM"
}'
```

- Response:
```json
{
    "payment_id": "pay_pvLYaf7aejhEVszi9OnZ",
    "merchant_id": "merchant_1726046328",
    "status": "requires_confirmation",
    "amount": 6540,
    "net_amount": 6540,
    "shipping_cost": null,
    "amount_capturable": 0,
    "amount_received": null,
    "connector": null,
    "client_secret": "pay_pvLYaf7aejhEVszi9OnZ_secret_a9hynS88hC0oz7LNRjFc",
    "created": "2024-11-06T18:21:43.625Z",
    "currency": "USD",
    "customer_id": "StripeCustomer",
    "customer": {
        "id": "StripeCustomer",
        "name": "John Doe",
        "email": "guest@example.com",
        "phone": "999999999",
        "phone_country_code": "+65"
    },
    "description": "Its my first payment request",
    "refunds": null,
    "disputes": null,
    "mandate_id": null,
    "mandate_data": null,
    "setup_future_usage": null,
    "off_session": null,
    "capture_on": null,
    "capture_method": "automatic",
    "payment_method": "card",
    "payment_method_data": {
        "card": {
            "last4": "4242",
            "card_type": null,
            "card_network": null,
            "card_issuer": null,
            "card_issuing_country": null,
            "card_isin": "424242",
            "card_extended_bin": null,
            "card_exp_month": "10",
            "card_exp_year": "25",
            "card_holder_name": null,
            "payment_checks": null,
            "authentication_data": null
        },
        "billing": null
    },
    "payment_token": "token_btocKPXDGHw1UKcvTpMW",
    "shipping": {
        "address": {
            "city": "San Fransico",
            "country": "US",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "California",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        },
        "email": null
    },
    "billing": {
        "address": {
            "city": "San Fransico",
            "country": "US",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "California",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        },
        "email": null
    },
    "order_details": null,
    "email": "guest@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "return_url": "https://google.com/",
    "authentication_type": "no_three_ds",
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "next_action": null,
    "cancellation_reason": null,
    "error_code": null,
    "error_message": null,
    "unified_code": null,
    "unified_message": null,
    "payment_experience": null,
    "payment_method_type": "credit",
    "connector_label": null,
    "business_country": null,
    "business_label": "default",
    "business_sub_label": null,
    "allowed_payment_method_types": null,
    "ephemeral_key": {
        "customer_id": "StripeCustomer",
        "created_at": 1730917303,
        "expires": 1730920903,
        "secret": "epk_11b7865dffb2468e8d16f29afcf8677f"
    },
    "manual_retry_allowed": null,
    "connector_transaction_id": null,
    "frm_message": null,
    "metadata": {
        "udf1": "value1",
        "login_date": "2019-09-10T10:11:12Z",
        "new_customer": "true"
    },
    "connector_metadata": null,
    "feature_metadata": null,
    "reference_id": null,
    "payment_link": null,
    "profile_id": "pro_v5sFoHe80OeiUlIonocM",
    "surcharge_details": null,
    "attempt_count": 1,
    "merchant_decision": null,
    "merchant_connector_id": null,
    "incremental_authorization_allowed": null,
    "authorization_count": null,
    "incremental_authorizations": null,
    "external_authentication_details": null,
    "external_3ds_authentication_attempted": false,
    "expires_on": "2024-11-06T18:36:43.625Z",
    "fingerprint": null,
    "browser_info": null,
    "payment_method_id": null,
    "payment_method_status": null,
    "updated": "2024-11-06T18:21:43.669Z",
    "charges": null,
    "frm_metadata": null,
    "merchant_order_reference_id": null,
    "order_tax_amount": null,
    "connector_mandate_id": null
}
```

Audit log will get generated and can be viewed in hyperswitch-audit-events topic in kafka with `PaymentCreate` event-type.

Screenshot 2024-11-06 at 11 52 00 PM

Now hit the `Payments - Confirm` endpoint, and audit log will get generated with `PaymentConfirm` event-type.

image

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

### CODE REVIEW

**Comment by Rutam21** [comment]
Please review and suggest changes, if any.

cc: @Isampras @ShivanshMathurJuspay @ivor11

**Comment by lsampras** [comment]
Hey @Rutam21 ,
Can you share the event json or a screenshot of the event,
Can refer to pr #4166 for reference,

In this case the PaymentCreate event should be created when you hit the payment create endpoint

**Comment by Rutam21** [comment]
@lsampras I checked #4166, can you please point me out how I can get a event screenhsot or event json for this update? It seems like you were using something similar to Postman to hit the API endpoint. If you could please let me know the steps, I would follow along and update.

**Comment by maverox** [comment]
> @lsampras I checked #4166, can you please point me out how I can get a event screenhsot or event json for this update? It seems like you were using something similar to Postman to hit the API endpoint. If you could please let me know the steps, I would follow along and update.

For the UI in this screenshot, you can find the docs to set up Kafka, kafka-ui (the interface in the screenshot) and ClickHouse using Docker Compose here: https://github.com/juspay/hyperswitch/tree/main/crates/analytics/docs

and then try generating said events and monitor logs in kafka-ui.

Also the docs are self-explanatory but still if in any doubt ping us in [this](https://hyperswitch-io.slack.com/archives/C04JXRZ338A) slack channel

**Comment by Rutam21** [comment]
@maverox I tried updating the respective `toml` files and then starting the app using docker-compose. But this errors out while starting the `hyperswitch-server-1`. Please let me know if there are some additional settings that I am missing here. Thanks.

Screenshot 2024-10-31 050533

**Review by tsdk02 — APPROVED** [review]

**Comment by Rutam21** [comment]
Thanks @tsdk02 for testing the changes and updating them in the PR description.

**Review by Chethan-rao — APPROVED** [review]

**Pull request merged**
